config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :employees, only: [:index, :new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  expose :employees, ->{ Employee.all }
  expose :employee

  def create
    Employee.create(employee_params)

    redirect_to employees_path
  end

  private

  def employee_params
    params.require(:employee).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
  def employee_name(employee)
    EmployeePresenter.new(employee, self).present
  end
end

app/views/employees/_form.html.haml
= form_for employee, url: employees_path, method: :post do |form|
  = form.label :name
  = form.text_field :name
  = form.submit

app/views/employees/edit.html.haml
%h2= employee_edit_title(employee)

= render 'form'

app/views/employees/index.html.haml
.main
  - employees.each do |employee|
    = employee_name(employee)
    = link_to 'Edit', edit_employee_path(employee)
    %br
  = link_to 'Create an Employee', new_employee_path

app/views/employees/new.html.haml
= render 'form'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>INeedAHero</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>